name: listen_to_my_tracks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.2
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  connectivity_plus: ^7.0.0
  equatable: ^2.0.7
  google_fonts: ^6.3.2
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
